name = "GridTools"
uuid = "7b5ac5b5-766a-43aa-b6dd-7a7de315d9f2"
authors = ["Jeffrey Zweidler"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
