spack:
  specs:
#  - python@3.10
#  - py-pip
#  - boost
  - cmake@3.30.2
#  - py-cupy cuda_arch=60 ^cuda+allow-unsupported-compilers ^nccl+cuda cuda_arch=60 ^cudnn@:8
#  - julia
  view: true
  concretizer:
    unify: true